### ISSUE TITLE
Doesn't build on linux : missing 'os_open_file_dialog'

### ISSUE THREAD

**Issue by JodiTheTigger** [machinamentum/Simp#1]
Oh no!

:-)

**Comment by machinamentum** [comment]
Hmm.. I'll get to this sometime this week but since dialog windows is a luxury on Linux rather than a given, it's quite involved to do this without a dedicated windowing kit.

**Comment by machinamentum** [comment]
Temporarily fixed by f806f0b8da283908695f3c81fb1c365609010174.

**Comment by JodiTheTigger** [comment]
Good work!

Now builds (and runs) fine!

Thanks.
